### ISSUE TITLE
Сhanging GEOSERVER_DATA_DIR breaks the container

### ISSUE THREAD

**Issue by P0linom** [kartoza/docker-geoserver#435] opened 2022-07-29 07:31 UTC
If `GEOSERVER_DATA_DIR` change to `/opt/geoserver/data` and volume has param `external: true`, then in logs: 

```
Creating /opt/geoserver/data/user_projections directory
mkdir: cannot create directory ‘/opt/geoserver/data/user_projections’: Permission denied
cp: cannot create regular file '/opt/geoserver/data/user_projections/epsg.properties': No such file or directory
```
and many of the same errors, as a result, the geoserver does not start.

docker-compose file:
```
volumes:
   geoserver-data-br:
     external: true

services:
   geoserver-br:
      image: kartoza/geoserver:2.21.0
      volumes:
        - geoserver-data-br:/opt/geoserver/data
      ports:
        - "8600:8080"
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data
```

**Comment by NyakudyaA** [comment] 2022-07-29 07:41
This is caused by running the image using a dedicated user. The GeoServer data directory is created during build and chown happens there. I have a fix for this in https://github.com/NyakudyaA/docker-geoserver/tree/gosu but I just need to figure out how to fix the issue with other data directories that are created by geoserver to have the correct permissions as indicated in https://github.com/NyakudyaA/docker-geoserver/blob/gosu/scripts/entrypoint.sh#L85

**Comment by poperne** [comment] 2022-08-02 07:12
@NyakudyaA  yeah, the issue happens when I am trying to launch a container with user - geoserver, with id 1000. When changing to root user, everything works as expected. 
Thank you!

**Comment by NyakudyaA** [comment] 2022-08-02 10:44
@P0linom Can you test that PR I have and see if it fixes your issue

**Closed as completed** 2022-08-04 09:44 UTC
